### ISSUE TITLE
Error displaying long text

### ISSUE THREAD

**Issue by AXCWG** [Aegrithas/mc-rcon-rs#1]
If return from server contains texts too long, the client error and exits: 

example: 

```
> help
/skin 
...... (roughly 3000 chars) 
|start|stop|reload|status|view)/starterkit [help|info|choose|add|set|deactivate|activate|give|list|reload|reset]/sk [help|info|choos
```

there should be outputs after it but it stops there. after typing anything, it returns an error: 

IO(Custom { kind: Other, error: "response packet id mismatched with login packet id" })

is it some kind of limit with rcon protocol or it's not correct?

**Comment by Aegrithas** [comment]
Ah, yes. There is a known issue with Minecraft's implementation of RCON that makes it hard to tell how long responses will be if they're longer than a certain number of characters (4096 if I recall correctly). As such, I opted to assume it would never happen, until someone (apparently, you) actually ran into this issue. I will work on fixing it, but it might not be super quick. If you need a quicker solution, let me know and I can make a temporary fix that will just ignore everything after the first 4096 characters.

**Comment by AXCWG** [comment]
> Ah, yes. There is a known issue with Minecraft's implementation of RCON that makes it hard to tell how long responses will be if they're longer than a certain number of characters (4096 if I recall correctly). As such, I opted to assume it would never happen, until someone (apparently, you) actually ran into this issue. I will work on fixing it, but it might not be super quick. If you need a quicker solution, let me know and I can make a temporary fix that will just ignore everything after the first 4096 characters.

It's ok and my case is not very urgent. Thank you.

**Comment by Aegrithas** [comment]
Alright, you should be good now, just update to version `0.1.1`.
